spring:
  batch:
    job:
      names: ${job.name:NONE}
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      data-locations: classpath:person.sql